### ISSUE TITLE
Design the App Architecture

### ISSUE THREAD

**Issue by mdnazisharman2803** [global-hacktoberfest22/The-Dart-Playground#1]
Implement design of the application using Adobe/Figma
- LogIn Screen
- SignUp Screen
- Interest Selection Screen
- Home Screen

Add your design in readme file

**Comment by baimamboukar** [comment]
This sounds good. I would like to work on this 👀 @fz3hra @victoriaEssien

**Comment by misteral1009** [comment]
It's done, i just created the pull request
